# Generated by Django 5.1.3 on 2025-03-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponguser',
            name='last_login_device',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ponguser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ponguser',
            name='last_otp_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
