# Generated by Django 5.1.3 on 2025-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_api', '0004_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('finished', 'Finished'), ('aborted', 'Aborted')], default='created', max_length=20),
        ),
    ]
