# Generated by Django 5.1.3 on 2025-05-19 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_api', '0006_alter_match_points_player_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='points_player_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points_player_2',
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
