# Generated by Django 5.1.3 on 2025-05-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_api', '0007_remove_match_points_player_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='points_player_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='points_player_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
