# Generated by Django 5.1.3 on 2025-06-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_api', '0010_tournament_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'managed': False},
        ),
    ]
