# Generated by Django 5.1.3 on 2025-07-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_api', '0011_alter_tournament_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tournament',
            table='user_mgmt_api_tournament',
        ),
    ]
