# Generated by Django 5.1.3 on 2025-08-03 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_api', '0012_alter_tournament_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponguser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
