# Generated by Django 5.1.3 on 2025-08-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_api', '0013_add_profile_image_and_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponguser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
