# Generated by Django 5.1.3 on 2025-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_api', '0005_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='points_player_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='points_player_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
