FROM python:3.11-alpine

RUN apk add --no-cache gcc musl-dev postgresql-dev

ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

WORKDIR /app

ENV VIRTUAL_ENV=/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV APP_PORT=8000

RUN python -m venv $VIRTUAL_ENV && $VIRTUAL_ENV/bin/pip install --no-cache-dir --upgrade pip setuptools wheel
